// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile/SystemMsgPB.proto

package com.google.protobuf;

public final class SystemMsgPB {
  private SystemMsgPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.protobuf.SystemMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息CODE 没有一个游戏自己都一个code对应Message的列表
     * </pre>
     *
     * <code>optional int32 msgCode = 1;</code>
     */
    boolean hasMsgCode();
    /**
     * <pre>
     *消息CODE 没有一个游戏自己都一个code对应Message的列表
     * </pre>
     *
     * <code>optional int32 msgCode = 1;</code>
     */
    int getMsgCode();

    /**
     * <pre>
     *bytes是否是MSG数组字节流
     * </pre>
     *
     * <code>optional bool isMsgArray = 2;</code>
     */
    boolean hasIsMsgArray();
    /**
     * <pre>
     *bytes是否是MSG数组字节流
     * </pre>
     *
     * <code>optional bool isMsgArray = 2;</code>
     */
    boolean getIsMsgArray();

    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray> 
        getMsgBytesList();
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    com.google.protobuf.SystemMsgPB.SystemMsgByteArray getMsgBytes(int index);
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    int getMsgBytesCount();
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    java.util.List<? extends com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder> 
        getMsgBytesOrBuilderList();
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder getMsgBytesOrBuilder(
        int index);

    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    boolean hasClassName();
    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    java.lang.String getClassName();
    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();
  }
  /**
   * <pre>
   *optional bool isSysMsg = 4;//是否是系统消息 预留字段
   * </pre>
   *
   * Protobuf type {@code com.google.protobuf.SystemMsg}
   */
  public  static final class SystemMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.protobuf.SystemMsg)
      SystemMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SystemMsg.newBuilder() to construct.
    private SystemMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemMsg() {
      msgCode_ = 0;
      isMsgArray_ = false;
      msgBytes_ = java.util.Collections.emptyList();
      className_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SystemMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              msgCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isMsgArray_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                msgBytes_ = new java.util.ArrayList<com.google.protobuf.SystemMsgPB.SystemMsgByteArray>();
                mutable_bitField0_ |= 0x00000004;
              }
              msgBytes_.add(
                  input.readMessage(com.google.protobuf.SystemMsgPB.SystemMsgByteArray.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              className_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          msgBytes_ = java.util.Collections.unmodifiableList(msgBytes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.SystemMsgPB.SystemMsg.class, com.google.protobuf.SystemMsgPB.SystemMsg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGCODE_FIELD_NUMBER = 1;
    private int msgCode_;
    /**
     * <pre>
     *消息CODE 没有一个游戏自己都一个code对应Message的列表
     * </pre>
     *
     * <code>optional int32 msgCode = 1;</code>
     */
    public boolean hasMsgCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *消息CODE 没有一个游戏自己都一个code对应Message的列表
     * </pre>
     *
     * <code>optional int32 msgCode = 1;</code>
     */
    public int getMsgCode() {
      return msgCode_;
    }

    public static final int ISMSGARRAY_FIELD_NUMBER = 2;
    private boolean isMsgArray_;
    /**
     * <pre>
     *bytes是否是MSG数组字节流
     * </pre>
     *
     * <code>optional bool isMsgArray = 2;</code>
     */
    public boolean hasIsMsgArray() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *bytes是否是MSG数组字节流
     * </pre>
     *
     * <code>optional bool isMsgArray = 2;</code>
     */
    public boolean getIsMsgArray() {
      return isMsgArray_;
    }

    public static final int MSGBYTES_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray> msgBytes_;
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    public java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray> getMsgBytesList() {
      return msgBytes_;
    }
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    public java.util.List<? extends com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder> 
        getMsgBytesOrBuilderList() {
      return msgBytes_;
    }
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    public int getMsgBytesCount() {
      return msgBytes_.size();
    }
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    public com.google.protobuf.SystemMsgPB.SystemMsgByteArray getMsgBytes(int index) {
      return msgBytes_.get(index);
    }
    /**
     * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
     */
    public com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder getMsgBytesOrBuilder(
        int index) {
      return msgBytes_.get(index);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object className_;
    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *实体类类名
     * </pre>
     *
     * <code>optional string className = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isMsgArray_);
      }
      for (int i = 0; i < msgBytes_.size(); i++) {
        output.writeMessage(3, msgBytes_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, className_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isMsgArray_);
      }
      for (int i = 0; i < msgBytes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, msgBytes_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, className_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.SystemMsgPB.SystemMsg)) {
        return super.equals(obj);
      }
      com.google.protobuf.SystemMsgPB.SystemMsg other = (com.google.protobuf.SystemMsgPB.SystemMsg) obj;

      boolean result = true;
      result = result && (hasMsgCode() == other.hasMsgCode());
      if (hasMsgCode()) {
        result = result && (getMsgCode()
            == other.getMsgCode());
      }
      result = result && (hasIsMsgArray() == other.hasIsMsgArray());
      if (hasIsMsgArray()) {
        result = result && (getIsMsgArray()
            == other.getIsMsgArray());
      }
      result = result && getMsgBytesList()
          .equals(other.getMsgBytesList());
      result = result && (hasClassName() == other.hasClassName());
      if (hasClassName()) {
        result = result && getClassName()
            .equals(other.getClassName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgCode()) {
        hash = (37 * hash) + MSGCODE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgCode();
      }
      if (hasIsMsgArray()) {
        hash = (37 * hash) + ISMSGARRAY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsMsgArray());
      }
      if (getMsgBytesCount() > 0) {
        hash = (37 * hash) + MSGBYTES_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBytesList().hashCode();
      }
      if (hasClassName()) {
        hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
        hash = (53 * hash) + getClassName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.SystemMsgPB.SystemMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *optional bool isSysMsg = 4;//是否是系统消息 预留字段
     * </pre>
     *
     * Protobuf type {@code com.google.protobuf.SystemMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.protobuf.SystemMsg)
        com.google.protobuf.SystemMsgPB.SystemMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.SystemMsgPB.SystemMsg.class, com.google.protobuf.SystemMsgPB.SystemMsg.Builder.class);
      }

      // Construct using com.google.protobuf.SystemMsgPB.SystemMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMsgBytesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isMsgArray_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (msgBytesBuilder_ == null) {
          msgBytes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          msgBytesBuilder_.clear();
        }
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsg_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsg getDefaultInstanceForType() {
        return com.google.protobuf.SystemMsgPB.SystemMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsg build() {
        com.google.protobuf.SystemMsgPB.SystemMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsg buildPartial() {
        com.google.protobuf.SystemMsgPB.SystemMsg result = new com.google.protobuf.SystemMsgPB.SystemMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgCode_ = msgCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isMsgArray_ = isMsgArray_;
        if (msgBytesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            msgBytes_ = java.util.Collections.unmodifiableList(msgBytes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.msgBytes_ = msgBytes_;
        } else {
          result.msgBytes_ = msgBytesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.className_ = className_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.SystemMsgPB.SystemMsg) {
          return mergeFrom((com.google.protobuf.SystemMsgPB.SystemMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.SystemMsgPB.SystemMsg other) {
        if (other == com.google.protobuf.SystemMsgPB.SystemMsg.getDefaultInstance()) return this;
        if (other.hasMsgCode()) {
          setMsgCode(other.getMsgCode());
        }
        if (other.hasIsMsgArray()) {
          setIsMsgArray(other.getIsMsgArray());
        }
        if (msgBytesBuilder_ == null) {
          if (!other.msgBytes_.isEmpty()) {
            if (msgBytes_.isEmpty()) {
              msgBytes_ = other.msgBytes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMsgBytesIsMutable();
              msgBytes_.addAll(other.msgBytes_);
            }
            onChanged();
          }
        } else {
          if (!other.msgBytes_.isEmpty()) {
            if (msgBytesBuilder_.isEmpty()) {
              msgBytesBuilder_.dispose();
              msgBytesBuilder_ = null;
              msgBytes_ = other.msgBytes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              msgBytesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMsgBytesFieldBuilder() : null;
            } else {
              msgBytesBuilder_.addAllMessages(other.msgBytes_);
            }
          }
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000008;
          className_ = other.className_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.SystemMsgPB.SystemMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.SystemMsgPB.SystemMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgCode_ ;
      /**
       * <pre>
       *消息CODE 没有一个游戏自己都一个code对应Message的列表
       * </pre>
       *
       * <code>optional int32 msgCode = 1;</code>
       */
      public boolean hasMsgCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *消息CODE 没有一个游戏自己都一个code对应Message的列表
       * </pre>
       *
       * <code>optional int32 msgCode = 1;</code>
       */
      public int getMsgCode() {
        return msgCode_;
      }
      /**
       * <pre>
       *消息CODE 没有一个游戏自己都一个code对应Message的列表
       * </pre>
       *
       * <code>optional int32 msgCode = 1;</code>
       */
      public Builder setMsgCode(int value) {
        bitField0_ |= 0x00000001;
        msgCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息CODE 没有一个游戏自己都一个code对应Message的列表
       * </pre>
       *
       * <code>optional int32 msgCode = 1;</code>
       */
      public Builder clearMsgCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgCode_ = 0;
        onChanged();
        return this;
      }

      private boolean isMsgArray_ ;
      /**
       * <pre>
       *bytes是否是MSG数组字节流
       * </pre>
       *
       * <code>optional bool isMsgArray = 2;</code>
       */
      public boolean hasIsMsgArray() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *bytes是否是MSG数组字节流
       * </pre>
       *
       * <code>optional bool isMsgArray = 2;</code>
       */
      public boolean getIsMsgArray() {
        return isMsgArray_;
      }
      /**
       * <pre>
       *bytes是否是MSG数组字节流
       * </pre>
       *
       * <code>optional bool isMsgArray = 2;</code>
       */
      public Builder setIsMsgArray(boolean value) {
        bitField0_ |= 0x00000002;
        isMsgArray_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *bytes是否是MSG数组字节流
       * </pre>
       *
       * <code>optional bool isMsgArray = 2;</code>
       */
      public Builder clearIsMsgArray() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isMsgArray_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray> msgBytes_ =
        java.util.Collections.emptyList();
      private void ensureMsgBytesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          msgBytes_ = new java.util.ArrayList<com.google.protobuf.SystemMsgPB.SystemMsgByteArray>(msgBytes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.SystemMsgPB.SystemMsgByteArray, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder, com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder> msgBytesBuilder_;

      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray> getMsgBytesList() {
        if (msgBytesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgBytes_);
        } else {
          return msgBytesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public int getMsgBytesCount() {
        if (msgBytesBuilder_ == null) {
          return msgBytes_.size();
        } else {
          return msgBytesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray getMsgBytes(int index) {
        if (msgBytesBuilder_ == null) {
          return msgBytes_.get(index);
        } else {
          return msgBytesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder setMsgBytes(
          int index, com.google.protobuf.SystemMsgPB.SystemMsgByteArray value) {
        if (msgBytesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgBytesIsMutable();
          msgBytes_.set(index, value);
          onChanged();
        } else {
          msgBytesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder setMsgBytes(
          int index, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder builderForValue) {
        if (msgBytesBuilder_ == null) {
          ensureMsgBytesIsMutable();
          msgBytes_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgBytesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder addMsgBytes(com.google.protobuf.SystemMsgPB.SystemMsgByteArray value) {
        if (msgBytesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgBytesIsMutable();
          msgBytes_.add(value);
          onChanged();
        } else {
          msgBytesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder addMsgBytes(
          int index, com.google.protobuf.SystemMsgPB.SystemMsgByteArray value) {
        if (msgBytesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgBytesIsMutable();
          msgBytes_.add(index, value);
          onChanged();
        } else {
          msgBytesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder addMsgBytes(
          com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder builderForValue) {
        if (msgBytesBuilder_ == null) {
          ensureMsgBytesIsMutable();
          msgBytes_.add(builderForValue.build());
          onChanged();
        } else {
          msgBytesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder addMsgBytes(
          int index, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder builderForValue) {
        if (msgBytesBuilder_ == null) {
          ensureMsgBytesIsMutable();
          msgBytes_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgBytesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder addAllMsgBytes(
          java.lang.Iterable<? extends com.google.protobuf.SystemMsgPB.SystemMsgByteArray> values) {
        if (msgBytesBuilder_ == null) {
          ensureMsgBytesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msgBytes_);
          onChanged();
        } else {
          msgBytesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder clearMsgBytes() {
        if (msgBytesBuilder_ == null) {
          msgBytes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          msgBytesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public Builder removeMsgBytes(int index) {
        if (msgBytesBuilder_ == null) {
          ensureMsgBytesIsMutable();
          msgBytes_.remove(index);
          onChanged();
        } else {
          msgBytesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder getMsgBytesBuilder(
          int index) {
        return getMsgBytesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder getMsgBytesOrBuilder(
          int index) {
        if (msgBytesBuilder_ == null) {
          return msgBytes_.get(index);  } else {
          return msgBytesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public java.util.List<? extends com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder> 
           getMsgBytesOrBuilderList() {
        if (msgBytesBuilder_ != null) {
          return msgBytesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgBytes_);
        }
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder addMsgBytesBuilder() {
        return getMsgBytesFieldBuilder().addBuilder(
            com.google.protobuf.SystemMsgPB.SystemMsgByteArray.getDefaultInstance());
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder addMsgBytesBuilder(
          int index) {
        return getMsgBytesFieldBuilder().addBuilder(
            index, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.getDefaultInstance());
      }
      /**
       * <code>repeated .com.google.protobuf.SystemMsgByteArray msgBytes = 3;</code>
       */
      public java.util.List<com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder> 
           getMsgBytesBuilderList() {
        return getMsgBytesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.SystemMsgPB.SystemMsgByteArray, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder, com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder> 
          getMsgBytesFieldBuilder() {
        if (msgBytesBuilder_ == null) {
          msgBytesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.SystemMsgPB.SystemMsgByteArray, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder, com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder>(
                  msgBytes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          msgBytes_ = null;
        }
        return msgBytesBuilder_;
      }

      private java.lang.Object className_ = "";
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            className_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *实体类类名
       * </pre>
       *
       * <code>optional string className = 4;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        className_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.protobuf.SystemMsg)
    }

    // @@protoc_insertion_point(class_scope:com.google.protobuf.SystemMsg)
    private static final com.google.protobuf.SystemMsgPB.SystemMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.SystemMsgPB.SystemMsg();
    }

    public static com.google.protobuf.SystemMsgPB.SystemMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SystemMsg>
        PARSER = new com.google.protobuf.AbstractParser<SystemMsg>() {
      @java.lang.Override
      public SystemMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SystemMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.SystemMsgPB.SystemMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SystemMsgByteArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.protobuf.SystemMsgByteArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes bytes = 1;</code>
     */
    boolean hasBytes();
    /**
     * <code>optional bytes bytes = 1;</code>
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code com.google.protobuf.SystemMsgByteArray}
   */
  public  static final class SystemMsgByteArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.protobuf.SystemMsgByteArray)
      SystemMsgByteArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SystemMsgByteArray.newBuilder() to construct.
    private SystemMsgByteArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemMsgByteArray() {
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SystemMsgByteArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              bytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsgByteArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsgByteArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.SystemMsgPB.SystemMsgByteArray.class, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder.class);
    }

    private int bitField0_;
    public static final int BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>optional bytes bytes = 1;</code>
     */
    public boolean hasBytes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes bytes = 1;</code>
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, bytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.SystemMsgPB.SystemMsgByteArray)) {
        return super.equals(obj);
      }
      com.google.protobuf.SystemMsgPB.SystemMsgByteArray other = (com.google.protobuf.SystemMsgPB.SystemMsgByteArray) obj;

      boolean result = true;
      result = result && (hasBytes() == other.hasBytes());
      if (hasBytes()) {
        result = result && getBytes()
            .equals(other.getBytes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBytes()) {
        hash = (37 * hash) + BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getBytes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.SystemMsgPB.SystemMsgByteArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.protobuf.SystemMsgByteArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.protobuf.SystemMsgByteArray)
        com.google.protobuf.SystemMsgPB.SystemMsgByteArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsgByteArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsgByteArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.SystemMsgPB.SystemMsgByteArray.class, com.google.protobuf.SystemMsgPB.SystemMsgByteArray.Builder.class);
      }

      // Construct using com.google.protobuf.SystemMsgPB.SystemMsgByteArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.SystemMsgPB.internal_static_com_google_protobuf_SystemMsgByteArray_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray getDefaultInstanceForType() {
        return com.google.protobuf.SystemMsgPB.SystemMsgByteArray.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray build() {
        com.google.protobuf.SystemMsgPB.SystemMsgByteArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protobuf.SystemMsgPB.SystemMsgByteArray buildPartial() {
        com.google.protobuf.SystemMsgPB.SystemMsgByteArray result = new com.google.protobuf.SystemMsgPB.SystemMsgByteArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bytes_ = bytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.SystemMsgPB.SystemMsgByteArray) {
          return mergeFrom((com.google.protobuf.SystemMsgPB.SystemMsgByteArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.SystemMsgPB.SystemMsgByteArray other) {
        if (other == com.google.protobuf.SystemMsgPB.SystemMsgByteArray.getDefaultInstance()) return this;
        if (other.hasBytes()) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.SystemMsgPB.SystemMsgByteArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.SystemMsgPB.SystemMsgByteArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytes = 1;</code>
       */
      public boolean hasBytes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes bytes = 1;</code>
       */
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>optional bytes bytes = 1;</code>
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytes = 1;</code>
       */
      public Builder clearBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.protobuf.SystemMsgByteArray)
    }

    // @@protoc_insertion_point(class_scope:com.google.protobuf.SystemMsgByteArray)
    private static final com.google.protobuf.SystemMsgPB.SystemMsgByteArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.SystemMsgPB.SystemMsgByteArray();
    }

    public static com.google.protobuf.SystemMsgPB.SystemMsgByteArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SystemMsgByteArray>
        PARSER = new com.google.protobuf.AbstractParser<SystemMsgByteArray>() {
      @java.lang.Override
      public SystemMsgByteArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SystemMsgByteArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemMsgByteArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemMsgByteArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.SystemMsgPB.SystemMsgByteArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_protobuf_SystemMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_protobuf_SystemMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_protobuf_SystemMsgByteArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_protobuf_SystemMsgByteArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protofile/SystemMsgPB.proto\022\023com.googl" +
      "e.protobuf\"~\n\tSystemMsg\022\017\n\007msgCode\030\001 \001(\005" +
      "\022\022\n\nisMsgArray\030\002 \001(\010\0229\n\010msgBytes\030\003 \003(\0132\'" +
      ".com.google.protobuf.SystemMsgByteArray\022" +
      "\021\n\tclassName\030\004 \001(\t\"#\n\022SystemMsgByteArray" +
      "\022\r\n\005bytes\030\001 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_google_protobuf_SystemMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_protobuf_SystemMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_protobuf_SystemMsg_descriptor,
        new java.lang.String[] { "MsgCode", "IsMsgArray", "MsgBytes", "ClassName", });
    internal_static_com_google_protobuf_SystemMsgByteArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_protobuf_SystemMsgByteArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_protobuf_SystemMsgByteArray_descriptor,
        new java.lang.String[] { "Bytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
